### ISSUE TITLE
COCO segmentation code

### ISSUE THREAD

**Issue by zhaozhengChen** [halbielee/EPS#11]
Hi authors,
[deeplab-pytorch](https://github.com/kazuto1011/deeplab-pytorch) only support code for VOC and COCO-Stuff, how can I use this repo to run segmentation on MS-COCO 2014?

**Comment by halbielee** [comment]
Hello @zhaozhengChen,

You need to change the dataloader part for MS-COCO.
(data path, the number of classes)

**Comment by zhaozhengChen** [comment]
Thanks!

**Comment by Italy2006** [comment]
> Hello @zhaozhengChen,
> 
> You need to change the dataloader part for MS-COCO. (data path, the number of classes)

Can you provide the corresponding setting？ Thanks！
