### ISSUE TITLE
About the color map of coco 2014

### ISSUE THREAD

**Issue by XuYin94** [halbielee/EPS#14]
Thanks for your wonderful work on WSSS.

Could you provide the color map (palette) in your work (on MS coco 2014) for segmentation visualization?

**Comment by halbielee** [comment]
Sorry for the late reply. 

I just used the color map from PASCAL VOC 2012. 
If you use PIL module, when loading the color image from PASCAL VOC 2012, you can extract the color palette!

(see Image.getpalette() / Image.putpalette())
