### ISSUE TITLE
hyper-parameters about CRF?

### ISSUE THREAD

**Issue by pigcv** [halbielee/EPS#5]
Hi! Thanks for you code! This repo doesn't provided detailed hyper-parameters (i.e, crf_t, alpha) when applying dCRF to the pseudo CAM label, can you provide them?

**Comment by halbielee** [comment]
Hello, @pigcv 

Thanks for your interest.

We conducted an experiment for comparing the performance of pseudo-masks. We also observed the performance when applying dCRF. We tested various CRF hyper-parameters based on the previous papers and chose them with the best performance. We referred to the official code/paper of [DeepLab](http://liangchiehchen.com/projects/DeepLab_Models.html), PSA(https://github.com/jiwoon-ahn/psa), and [OAA](https://github.com/PengtaoJiang/OAA).
The difference in the performance according to the hyper-parameters among the papers is not that big, but not negligible.
Finally, we chose the hyper-parameters of DeepLab-V2 (ResNet101-based) for dCRF in the experiments. Please see [the website of DeepLabV2](http://liangchiehchen.com/projects/DeepLabv2_resnet.html) for them. By the way, the hyper-parameters are different according to the backbone network in the official DeepLab code. 

If you have any question, please leave an issue here :)

Thanks!

**Comment by pigcv** [comment]
Thanks for your reply~
