### ISSUE TITLE
COCO training codes too.

### ISSUE THREAD

**Issue by Sierkinhane** [halbielee/EPS#7]

**Comment by halbielee** [comment]
Hello, @Sierkinhane 

I will provide the training code & dataset for COCO soon!

**Comment by halbielee** [comment]
Hello @Sierkinhane

I uploaded the training data and training code for MS-COCO 2014
Please see [another issue](https://github.com/halbielee/EPS/issues/6) or [README.md](https://github.com/halbielee/EPS/blob/main/README.md) for details.
