### ISSUE TITLE
COCO checkpoint

### ISSUE THREAD

**Issue by allenwu97** [halbielee/EPS#8]
When I use ‘coco_cls.pth’ and ‘resnet38_cls’ to generate CAM, the eval result is very low(only 1.3%). But when I use ‘coco_eps.pth’ and ‘resnet38_eps’, the eval result is correct. Do you have any suggestions for this problem？

**Comment by halbielee** [comment]
Hello allenwu97.

We changed the link for the checkpint! Please check  it!
